<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { approveFarmer, listFarmerApplications, rejectFarmer } from '../../api/farmers'
import type { FarmerApplicationView } from '../../api/auth'
const applications=ref<FarmerApplicationView[]>([]); const loading=ref(true); const error=ref(''); const reasons=ref<Record<number,string>>({}); const busy=ref<number|null>(null)
async function load(){loading.value=true;error.value='';try{applications.value=await listFarmerApplications()}catch{error.value='农户申请加载失败，请稍后重试'}finally{loading.value=false}}
async function decide(id:number, action:'approve'|'reject'){if(action==='reject'&&!reasons.value[id]?.trim()){error.value='拒绝申请时必须填写原因。';return};busy.value=id;try{if(action==='approve')await approveFarmer(id);else await rejectFarmer(id,reasons.value[id]);await load()}catch{error.value='审核操作失败，请稍后重试'}finally{busy.value=null}}
onMounted(load)
</script>
<template><main class="product-management-page"><header class="orders-header"><p class="eyebrow">管理员后台</p><h1>农户入驻审核</h1><p>审核农户资质，审核通过后方可登录卖家中心。</p></header><p v-if="error" class="form-error" role="alert">{{ error }}</p><section v-if="loading" class="orders-empty">正在加载申请...</section><section v-else-if="!applications.length" class="orders-empty"><h2>暂无待审核申请</h2></section><section v-else class="management-grid"><article v-for="item in applications" :key="item.id" class="management-card"><div class="management-card-header"><div><p class="eyebrow">申请 #{{ item.id }}</p><h2>{{ item.realName }}</h2></div><span class="status-chip">{{ item.status }}</span></div><dl class="detail-list"><div><dt>手机号</dt><dd>{{ item.phone }}</dd></div><div><dt>身份证号</dt><dd>{{ item.idCard }}</dd></div><div><dt>地区</dt><dd>{{ item.province }}{{ item.city }}{{ item.district }}</dd></div><div><dt>详细地址</dt><dd>{{ item.detailAddress }}</dd></div><div><dt>主营品类</dt><dd>{{ item.category }}</dd></div><div><dt>营业执照</dt><dd>{{ item.licenseNo || '未填写' }}</dd></div></dl><textarea v-model="reasons[item.id]" placeholder="拒绝时填写原因"></textarea><div class="management-actions"><button type="button" :disabled="busy===item.id" @click="decide(item.id,'approve')">{{ busy===item.id?'处理中…':'通过审核' }}</button><button type="button" class="secondary-button" :disabled="busy===item.id" @click="decide(item.id,'reject')">拒绝申请</button></div></article></section></main></template>
