<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { listFarmerProducts, resubmitProduct, takeProductOffSale, type ProductDetail, type ProductStatus } from '../../api/products'
const products = ref<ProductDetail[]>([]); const loading = ref(true); const error = ref(''); const busyId = ref<number | null>(null)
const labels: Record<ProductStatus, string> = { PENDING_REVIEW: '待审核', ON_SALE: '已上架', OFF_SALE: '已下架', REJECTED: '已拒绝' }
async function load() { loading.value = true; try { products.value = await listFarmerProducts() } catch { error.value = '商品列表加载失败，请稍后重试' } finally { loading.value = false } }
async function change(id: number, action: () => Promise<unknown>) { busyId.value = id; error.value = ''; try { await action(); await load() } catch { error.value = '操作失败，请稍后重试' } finally { busyId.value = null } }
onMounted(load)
</script>
<template><main class="orders-page product-management-page"><header class="orders-header"><RouterLink class="back-link" :to="{ name: 'home' }">返回商城</RouterLink><p class="eyebrow">农户中心</p><h1>我的商品</h1><p>查看审核状态，及时更新你的商品信息。</p><RouterLink class="secondary-link" :to="{ name: 'farmer-product-new' }">新建商品</RouterLink></header><p v-if="error" class="form-error" role="alert">{{ error }}</p><section v-if="loading" class="orders-empty">正在加载商品...</section><section v-else-if="!products.length" class="orders-empty"><h2>还没有商品</h2><p>发布第一个商品，开始助农销售。</p></section><section v-else class="order-list" aria-label="我的商品列表"><article v-for="product in products" :key="product.id" class="order-card product-review-card"><div class="product-review-main"><img :src="product.imageUrl" :alt="product.name"><div><p class="eyebrow">{{ product.categoryName }}</p><h2>{{ product.name }}</h2><p>库存 {{ product.stock }} · ¥{{ product.price }} · {{ product.originPlace }}</p><p v-if="product.reviewReason" class="review-reason">拒绝原因：{{ product.reviewReason }}</p></div><span class="order-status" :class="`status-${product.status.toLowerCase()}`">{{ labels[product.status] }}</span></div><div class="review-actions"><RouterLink v-if="product.status === 'REJECTED'" class="secondary-link" :to="{ name: 'farmer-product-edit', params: { id: product.id } }">修改并重新提交</RouterLink><button v-if="product.status === 'OFF_SALE'" type="button" :disabled="busyId === product.id" @click="change(product.id, () => resubmitProduct(product.id))">重新提交审核</button><button v-if="product.status === 'ON_SALE'" class="secondary-button" type="button" :disabled="busyId === product.id" @click="change(product.id, () => takeProductOffSale(product.id))">下架商品</button></div></article></section></main></template>
